### ISSUE TITLE
Fit within boxes

### ISSUE THREAD

**Issue by mtancock** [achapin/xwing-microhangars#10]
I've been a fan of Sir Willi's microhangars for a while, so was excited to see your attempt to pick up the mantle for the missing ships.

I also appreciate the attempts to automate this as much as possible, but based on the couple of ships I've printed so far, I think it shows the problems with the automation and the irregular nature of the ships.

The wonderful thing about Sir Willi's ships is how they always seems to exactly hold the ship tightly so it can't move around in the box, without "poking" in any direction leading to the danger of damage or the ability to move around / rotate in the box.

Last night I tried the LAAT and the Gauntlet. Unfortunately, neither are what I would call "secure".

The LAAT either "rattles" around in the box, or deforms the box leading to areas of the ship "poking" into the cardboard depending on how it's put in the box, which doesn't give me a great deal of confidence in the boxes protection.

Based on large models of Sir Willi's hangars, for the Gauntlet, I reenforced the large sides, as even with quite thick card, over such a huge area becomes a bit bendy. But the main issue is that the ship moves around in the hangar significantly because of the approximate triangular shape of the ship.

I haven't tried the Rogues or the Clone z95s yet—printed but not assembled—but based on the above experience, I'd expect the rogues to be probably ok as they're squarish. The clone z95s being a bit more triangular could mean they're also problematic. I can report back once I've tried.

I'm not sure that there's an automated solution possible to these issues unfortunately, but thought I'd bring them up in case you have any ideas.

Thanks again for your work on this and contributing to the x-wing community.

**Comment by achapin** [comment]
Hey mate,

Sorry to hear you've been having issues with the fit of the ships in the boxes. Can you verify that you're printing them at exactly 100% scale? Sometimes printers can be overzealous about making things "fit" when the page is from the web instead of from a PDF.

I've personally tested the LAAT and the Gauntlet myself, and found the measurements to be pretty spot-on. There's always going to be a little bit of wiggle room built-in, since I can't assume that everyone is the most precise with their cutting, folding and gluing. The overall outcome is way more protection than letting the models loose in a case, though.

![IMG_6176](https://user-images.githubusercontent.com/4753012/172475086-5dea076a-b6f2-49ff-a17a-d2a91057763b.jpeg)
![IMG_6177](https://user-images.githubusercontent.com/4753012/172475091-b9965fb1-5822-4019-89d6-9098a8a45f66.jpeg)
![IMG_6182](https://user-images.githubusercontent.com/4753012/172475093-4c11e4bd-c02d-4d90-bdb6-571766594c7b.jpeg)
![IMG_6183](https://user-images.githubusercontent.com/4753012/172475095-490617f2-46d9-43d2-b51a-6f8238a5969b.jpeg)

If you've got some alternative measurements you'd want to try out, let me know and I can send you a PDF that has them instead of the current defaults.

**Comment by mtancock** [comment]
Thanks for the reply @achapin

It's hard to know whether they're printed correctly. Maybe it would be possible to add a calibration option to print a 20mm x 20mm square like Sir Willi's cover sheets have or something to easily measure and ensure printing at the right size?

I printed them at 100% scale, which is what I do for everything else. 

I regonise the LAAT is a total pain because of it's shape. I spent ages trying to make my own box the right size (without success) before I discovered your project. I'll keep working on the dimensions for that one.

This is what my Gauntlet looks like on top of the box. 

![IMG_2757](https://user-images.githubusercontent.com/1439570/172571058-1c567d79-dcc3-434b-b75d-8492a3f8d2a2.jpeg)
![IMG_2756](https://user-images.githubusercontent.com/1439570/172571052-bc33f849-ceb9-43d4-80c0-c6be2ed4bf9a.jpeg)

Perspective makes this difficult but the bottom protrusions that sticks out from the engine are aligned with the edge of the box, which—depending on orientation—leaves about 15-20mm at both top and side, or about 30mm at the side with top and bottom being the correct dimension. 

Either is enough for fairly significant movement within the hangar, although as you correctly point out, still better protection than going naked with other ships!

I wonder if it would be better to try to align it diagonally like this: 
![CleanShot 2022-06-08 at 09 38 32@2x](https://user-images.githubusercontent.com/1439570/172572083-5c2f753e-965d-4915-8dfd-d8e73fddbaf9.png)

I'll try modifying this box like that and feedback if I make any progress.

Thank you for being so responsive.

**Comment by achapin** [comment]
That sideways orientation looks like it'd be worth a try! If you get the numbers I can try it out.

**Comment by mtancock** [comment]
Thanks. I did end up trying it myself. While it was there I messed around with the artwork too—not quite SirWilli level, but it would pass at a quick glance in my box of other ships. 

But regardless I think it works pretty nicely at this size (dodgy gluing excepted—was just using a glue stick I had on hand):

![IMG_2826](https://user-images.githubusercontent.com/1439570/173566143-d55e3d58-4442-4fbf-8549-6286d7f6691e.jpeg)
No internal photo sorry, but it doesn't deform the box, so I'm pretty happy.

The box dimensions I ended up with are **165 x 180 x 30 (in mm)** 

Having made the prototype, it could even go a touch smaller in one dimension but this seems pretty secure now, and as you point out because of unknown tolerances when making them (especially because this needs printing on multiple sheets) it's probably not worth taking it right to the edge.

I'm going to try the LAAT next! That's the really difficult one I think because it's such an odd shape.

Anyway, this can probably be closed :)
